version: "3.7"
services:
  simulator-server:
    image: registry.k8s.io/scheduler-simulator/simulator-backend:v0.1.1
    container_name: simulator-server
    environment:
      - PORT=1212
      - KUBE_SCHEDULER_SIMULATOR_ETCD_URL=http://simulator-cluster:2379
      - CORS_ALLOWED_ORIGIN_LIST=http://${SIMULATOR_EXTERNAL_IP:-localhost}:3000
      - KUBE_API_HOST=0.0.0.0
      - KUBE_API_PORT=3131
    ports:
      - "1212:1212"
      - "3131:3131"
    restart: always
    tty: true
  simulator-frontend:
    image: registry.k8s.io/scheduler-simulator/simulator-frontend:v0.1.1
    restart: always
    container_name: simulator-frontend
    environment:
      - HOST=0.0.0.0
      - BASE_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:1212
      - KUBE_API_SERVER_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:3131
    ports:
    - "3000:3000"
    tty: true
  simulator-cluster:
    image: registry.k8s.io/kwok/cluster:v0.5.0-k8s.v1.29.0
    container_name: simulator-cluster
    restart: always
    ports:
      - "8080:8080"
    command:
      - --etcd-prefix=/kube-scheduler-simulator
      - --disable-kube-scheduler
    environment:
      - KWOK_ETCD_PORT=2379
      - KWOK_KUBE_APISERVER_PORT=8080
    volumes:
      - simulator-etcd-data:/var/lib/etcd
volumes:
  simulator-etcd-data:
