version: "3.7"
services:
  simulator-server:
    image: registry.k8s.io/scheduler-simulator/simulator-backend:v0.1.1
    container_name: simulator-server
    environment:
      - PORT=1212
      - KUBE_SCHEDULER_SIMULATOR_ETCD_URL=http://127.0.0.1:32765
      - CORS_ALLOWED_ORIGIN_LIST=http://${SIMULATOR_EXTERNAL_IP:-localhost}:3000
      - KUBE_API_HOST=0.0.0.0
      - KUBE_API_PORT=32765
    ports:
      - "1212:1212"
      - "32765:32765"
    restart: always
    tty: true
    networks:
      - simulator-internal-network
  simulator-frontend:
    image: registry.k8s.io/scheduler-simulator/simulator-frontend:v0.1.1
    restart: always
    container_name: simulator-frontend
    environment:
      - HOST=0.0.0.0
      - BASE_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:1212
      - KUBE_API_SERVER_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:32765
    ports:
    - "3000:3000"
    tty: true
networks:
  simulator-internal-network:
    driver: bridge
