// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kubernetes-sigs/kube-scheduler-simulator/watcher (interfaces: ResourceEventProxy)

// Package mock_watcher is a generated GoMock package.
package mock_watcher

import (
	gomock "github.com/golang/mock/gomock"
	watch "k8s.io/apimachinery/pkg/watch"
	reflect "reflect"
)

// MockResourceEventProxy is a mock of ResourceEventProxy interface
type MockResourceEventProxy struct {
	ctrl     *gomock.Controller
	recorder *MockResourceEventProxyMockRecorder
}

// MockResourceEventProxyMockRecorder is the mock recorder for MockResourceEventProxy
type MockResourceEventProxyMockRecorder struct {
	mock *MockResourceEventProxy
}

// NewMockResourceEventProxy creates a new mock instance
func NewMockResourceEventProxy(ctrl *gomock.Controller) *MockResourceEventProxy {
	mock := &MockResourceEventProxy{ctrl: ctrl}
	mock.recorder = &MockResourceEventProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockResourceEventProxy) EXPECT() *MockResourceEventProxyMockRecorder {
	return m.recorder
}

// WatchErrorHandler mocks base method
func (m *MockResourceEventProxy) WatchErrorHandler(arg0 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WatchErrorHandler", arg0)
}

// WatchErrorHandler indicates an expected call of WatchErrorHandler
func (mr *MockResourceEventProxyMockRecorder) WatchErrorHandler(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchErrorHandler", reflect.TypeOf((*MockResourceEventProxy)(nil).WatchErrorHandler), arg0)
}

// WatchHandlerFunc mocks base method
func (m *MockResourceEventProxy) WatchHandlerFunc(arg0 watch.Interface) func(<-chan struct{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchHandlerFunc", arg0)
	ret0, _ := ret[0].(func(<-chan struct{}) error)
	return ret0
}

// WatchHandlerFunc indicates an expected call of WatchHandlerFunc
func (mr *MockResourceEventProxyMockRecorder) WatchHandlerFunc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchHandlerFunc", reflect.TypeOf((*MockResourceEventProxy)(nil).WatchHandlerFunc), arg0)
}
