// Code generated by MockGen. DO NOT EDIT.
// Source: sigs.k8s.io/kube-scheduler-simulator/simulator/resourcewatcher (interfaces: ResourceEventProxy)

// Package mock_resourcewatcher is a generated GoMock package.
package mock_resourcewatcher

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"

	streamwriter "sigs.k8s.io/kube-scheduler-simulator/simulator/resourcewatcher/streamwriter"
)

// MockResourceEventProxy is a mock of ResourceEventProxy interface.
type MockResourceEventProxy struct {
	ctrl     *gomock.Controller
	recorder *MockResourceEventProxyMockRecorder
}

// MockResourceEventProxyMockRecorder is the mock recorder for MockResourceEventProxy.
type MockResourceEventProxyMockRecorder struct {
	mock *MockResourceEventProxy
}

// NewMockResourceEventProxy creates a new mock instance.
func NewMockResourceEventProxy(ctrl *gomock.Controller) *MockResourceEventProxy {
	mock := &MockResourceEventProxy{ctrl: ctrl}
	mock.recorder = &MockResourceEventProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceEventProxy) EXPECT() *MockResourceEventProxyMockRecorder {
	return m.recorder
}

// LastResourceVersion mocks base method.
func (m *MockResourceEventProxy) LastResourceVersion() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastResourceVersion")
	ret0, _ := ret[0].(string)
	return ret0
}

// LastResourceVersion indicates an expected call of LastResourceVersion.
func (mr *MockResourceEventProxyMockRecorder) LastResourceVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastResourceVersion", reflect.TypeOf((*MockResourceEventProxy)(nil).LastResourceVersion))
}

// ListAndHandleItems mocks base method.
func (m *MockResourceEventProxy) ListAndHandleItems(arg0 cache.Lister) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAndHandleItems", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListAndHandleItems indicates an expected call of ListAndHandleItems.
func (mr *MockResourceEventProxyMockRecorder) ListAndHandleItems(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAndHandleItems", reflect.TypeOf((*MockResourceEventProxy)(nil).ListAndHandleItems), arg0)
}

// ResourceKind mocks base method.
func (m *MockResourceEventProxy) ResourceKind() streamwriter.ResourceKind {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourceKind")
	ret0, _ := ret[0].(streamwriter.ResourceKind)
	return ret0
}

// ResourceKind indicates an expected call of ResourceKind.
func (mr *MockResourceEventProxyMockRecorder) ResourceKind() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceKind", reflect.TypeOf((*MockResourceEventProxy)(nil).ResourceKind))
}

// RestClient mocks base method.
func (m *MockResourceEventProxy) RestClient() cache.Getter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestClient")
	ret0, _ := ret[0].(cache.Getter)
	return ret0
}

// RestClient indicates an expected call of RestClient.
func (mr *MockResourceEventProxyMockRecorder) RestClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestClient", reflect.TypeOf((*MockResourceEventProxy)(nil).RestClient))
}

// WatchAndHandleEvent mocks base method.
func (m *MockResourceEventProxy) WatchAndHandleEvent(arg0 watch.Interface, arg1 <-chan struct{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WatchAndHandleEvent", arg0, arg1)
}

// WatchAndHandleEvent indicates an expected call of WatchAndHandleEvent.
func (mr *MockResourceEventProxyMockRecorder) WatchAndHandleEvent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchAndHandleEvent", reflect.TypeOf((*MockResourceEventProxy)(nil).WatchAndHandleEvent), arg0, arg1)
}
