// Code generated by MockGen. DO NOT EDIT.
// Source: k8s.io/apimachinery/pkg/watch (interfaces: Interface)

// Package mock_resourcewatcher is a generated GoMock package.
package mock_resourcewatcher

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	watch "k8s.io/apimachinery/pkg/watch"
)

// MockWatchInterface is a mock of Interface interface.
type MockWatchInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWatchInterfaceMockRecorder
}

// MockWatchInterfaceMockRecorder is the mock recorder for MockWatchInterface.
type MockWatchInterfaceMockRecorder struct {
	mock *MockWatchInterface
}

// NewMockWatchInterface creates a new mock instance.
func NewMockWatchInterface(ctrl *gomock.Controller) *MockWatchInterface {
	mock := &MockWatchInterface{ctrl: ctrl}
	mock.recorder = &MockWatchInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatchInterface) EXPECT() *MockWatchInterfaceMockRecorder {
	return m.recorder
}

// ResultChan mocks base method.
func (m *MockWatchInterface) ResultChan() <-chan watch.Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResultChan")
	ret0, _ := ret[0].(<-chan watch.Event)
	return ret0
}

// ResultChan indicates an expected call of ResultChan.
func (mr *MockWatchInterfaceMockRecorder) ResultChan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResultChan", reflect.TypeOf((*MockWatchInterface)(nil).ResultChan))
}

// Stop mocks base method.
func (m *MockWatchInterface) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockWatchInterfaceMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockWatchInterface)(nil).Stop))
}
