// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kubernetes-sigs/kube-scheduler-simulator/export (interfaces: PersistentVolumeService)

// Package mock_export is a generated GoMock package.
package mock_export

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/api/core/v1"
	v10 "k8s.io/client-go/applyconfigurations/core/v1"
)

// MockPersistentVolumeService is a mock of PersistentVolumeService interface.
type MockPersistentVolumeService struct {
	ctrl     *gomock.Controller
	recorder *MockPersistentVolumeServiceMockRecorder
}

// MockPersistentVolumeServiceMockRecorder is the mock recorder for MockPersistentVolumeService.
type MockPersistentVolumeServiceMockRecorder struct {
	mock *MockPersistentVolumeService
}

// NewMockPersistentVolumeService creates a new mock instance.
func NewMockPersistentVolumeService(ctrl *gomock.Controller) *MockPersistentVolumeService {
	mock := &MockPersistentVolumeService{ctrl: ctrl}
	mock.recorder = &MockPersistentVolumeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersistentVolumeService) EXPECT() *MockPersistentVolumeServiceMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockPersistentVolumeService) Apply(arg0 context.Context, arg1 *v10.PersistentVolumeApplyConfiguration) (*v1.PersistentVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", arg0, arg1)
	ret0, _ := ret[0].(*v1.PersistentVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Apply indicates an expected call of Apply.
func (mr *MockPersistentVolumeServiceMockRecorder) Apply(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockPersistentVolumeService)(nil).Apply), arg0, arg1)
}

// List mocks base method.
func (m *MockPersistentVolumeService) List(arg0 context.Context) (*v1.PersistentVolumeList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].(*v1.PersistentVolumeList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPersistentVolumeServiceMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPersistentVolumeService)(nil).List), arg0)
}
