// Code generated by MockGen. DO NOT EDIT.
// Source: k8s.io/kubernetes/pkg/scheduler/framework (interfaces: PreFilterPlugin,FilterPlugin,PostFilterPlugin,PreScorePlugin,ScorePlugin,ScoreExtensions,PermitPlugin,BindPlugin,PreBindPlugin,PostBindPlugin,ReservePlugin)
//
// Generated by this command:
//
//	mockgen -destination=./mock/framework.go -package=plugin k8s.io/kubernetes/pkg/scheduler/framework PreFilterPlugin,FilterPlugin,PostFilterPlugin,PreScorePlugin,ScorePlugin,ScoreExtensions,PermitPlugin,BindPlugin,PreBindPlugin,PostBindPlugin,ReservePlugin
//

// Package plugin is a generated GoMock package.
package plugin

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
	framework "k8s.io/kubernetes/pkg/scheduler/framework"
)

// MockPreFilterPlugin is a mock of PreFilterPlugin interface.
type MockPreFilterPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPreFilterPluginMockRecorder
	isgomock struct{}
}

// MockPreFilterPluginMockRecorder is the mock recorder for MockPreFilterPlugin.
type MockPreFilterPluginMockRecorder struct {
	mock *MockPreFilterPlugin
}

// NewMockPreFilterPlugin creates a new mock instance.
func NewMockPreFilterPlugin(ctrl *gomock.Controller) *MockPreFilterPlugin {
	mock := &MockPreFilterPlugin{ctrl: ctrl}
	mock.recorder = &MockPreFilterPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreFilterPlugin) EXPECT() *MockPreFilterPluginMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockPreFilterPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPreFilterPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPreFilterPlugin)(nil).Name))
}

// PreFilter mocks base method.
func (m *MockPreFilterPlugin) PreFilter(ctx context.Context, state *framework.CycleState, p *v1.Pod) (*framework.PreFilterResult, *framework.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreFilter", ctx, state, p)
	ret0, _ := ret[0].(*framework.PreFilterResult)
	ret1, _ := ret[1].(*framework.Status)
	return ret0, ret1
}

// PreFilter indicates an expected call of PreFilter.
func (mr *MockPreFilterPluginMockRecorder) PreFilter(ctx, state, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreFilter", reflect.TypeOf((*MockPreFilterPlugin)(nil).PreFilter), ctx, state, p)
}

// PreFilterExtensions mocks base method.
func (m *MockPreFilterPlugin) PreFilterExtensions() framework.PreFilterExtensions {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreFilterExtensions")
	ret0, _ := ret[0].(framework.PreFilterExtensions)
	return ret0
}

// PreFilterExtensions indicates an expected call of PreFilterExtensions.
func (mr *MockPreFilterPluginMockRecorder) PreFilterExtensions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreFilterExtensions", reflect.TypeOf((*MockPreFilterPlugin)(nil).PreFilterExtensions))
}

// MockFilterPlugin is a mock of FilterPlugin interface.
type MockFilterPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockFilterPluginMockRecorder
	isgomock struct{}
}

// MockFilterPluginMockRecorder is the mock recorder for MockFilterPlugin.
type MockFilterPluginMockRecorder struct {
	mock *MockFilterPlugin
}

// NewMockFilterPlugin creates a new mock instance.
func NewMockFilterPlugin(ctrl *gomock.Controller) *MockFilterPlugin {
	mock := &MockFilterPlugin{ctrl: ctrl}
	mock.recorder = &MockFilterPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilterPlugin) EXPECT() *MockFilterPluginMockRecorder {
	return m.recorder
}

// Filter mocks base method.
func (m *MockFilterPlugin) Filter(ctx context.Context, state *framework.CycleState, pod *v1.Pod, nodeInfo *framework.NodeInfo) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, state, pod, nodeInfo)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// Filter indicates an expected call of Filter.
func (mr *MockFilterPluginMockRecorder) Filter(ctx, state, pod, nodeInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockFilterPlugin)(nil).Filter), ctx, state, pod, nodeInfo)
}

// Name mocks base method.
func (m *MockFilterPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockFilterPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockFilterPlugin)(nil).Name))
}

// MockPostFilterPlugin is a mock of PostFilterPlugin interface.
type MockPostFilterPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPostFilterPluginMockRecorder
	isgomock struct{}
}

// MockPostFilterPluginMockRecorder is the mock recorder for MockPostFilterPlugin.
type MockPostFilterPluginMockRecorder struct {
	mock *MockPostFilterPlugin
}

// NewMockPostFilterPlugin creates a new mock instance.
func NewMockPostFilterPlugin(ctrl *gomock.Controller) *MockPostFilterPlugin {
	mock := &MockPostFilterPlugin{ctrl: ctrl}
	mock.recorder = &MockPostFilterPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostFilterPlugin) EXPECT() *MockPostFilterPluginMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockPostFilterPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPostFilterPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPostFilterPlugin)(nil).Name))
}

// PostFilter mocks base method.
func (m *MockPostFilterPlugin) PostFilter(ctx context.Context, state *framework.CycleState, pod *v1.Pod, filteredNodeStatusMap framework.NodeToStatusMap) (*framework.PostFilterResult, *framework.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostFilter", ctx, state, pod, filteredNodeStatusMap)
	ret0, _ := ret[0].(*framework.PostFilterResult)
	ret1, _ := ret[1].(*framework.Status)
	return ret0, ret1
}

// PostFilter indicates an expected call of PostFilter.
func (mr *MockPostFilterPluginMockRecorder) PostFilter(ctx, state, pod, filteredNodeStatusMap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostFilter", reflect.TypeOf((*MockPostFilterPlugin)(nil).PostFilter), ctx, state, pod, filteredNodeStatusMap)
}

// MockPreScorePlugin is a mock of PreScorePlugin interface.
type MockPreScorePlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPreScorePluginMockRecorder
	isgomock struct{}
}

// MockPreScorePluginMockRecorder is the mock recorder for MockPreScorePlugin.
type MockPreScorePluginMockRecorder struct {
	mock *MockPreScorePlugin
}

// NewMockPreScorePlugin creates a new mock instance.
func NewMockPreScorePlugin(ctrl *gomock.Controller) *MockPreScorePlugin {
	mock := &MockPreScorePlugin{ctrl: ctrl}
	mock.recorder = &MockPreScorePluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreScorePlugin) EXPECT() *MockPreScorePluginMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockPreScorePlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPreScorePluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPreScorePlugin)(nil).Name))
}

// PreScore mocks base method.
func (m *MockPreScorePlugin) PreScore(ctx context.Context, state *framework.CycleState, pod *v1.Pod, nodes []*v1.Node) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreScore", ctx, state, pod, nodes)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// PreScore indicates an expected call of PreScore.
func (mr *MockPreScorePluginMockRecorder) PreScore(ctx, state, pod, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreScore", reflect.TypeOf((*MockPreScorePlugin)(nil).PreScore), ctx, state, pod, nodes)
}

// MockScorePlugin is a mock of ScorePlugin interface.
type MockScorePlugin struct {
	ctrl     *gomock.Controller
	recorder *MockScorePluginMockRecorder
	isgomock struct{}
}

// MockScorePluginMockRecorder is the mock recorder for MockScorePlugin.
type MockScorePluginMockRecorder struct {
	mock *MockScorePlugin
}

// NewMockScorePlugin creates a new mock instance.
func NewMockScorePlugin(ctrl *gomock.Controller) *MockScorePlugin {
	mock := &MockScorePlugin{ctrl: ctrl}
	mock.recorder = &MockScorePluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScorePlugin) EXPECT() *MockScorePluginMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockScorePlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockScorePluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockScorePlugin)(nil).Name))
}

// Score mocks base method.
func (m *MockScorePlugin) Score(ctx context.Context, state *framework.CycleState, p *v1.Pod, nodeName string) (int64, *framework.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Score", ctx, state, p, nodeName)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*framework.Status)
	return ret0, ret1
}

// Score indicates an expected call of Score.
func (mr *MockScorePluginMockRecorder) Score(ctx, state, p, nodeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Score", reflect.TypeOf((*MockScorePlugin)(nil).Score), ctx, state, p, nodeName)
}

// ScoreExtensions mocks base method.
func (m *MockScorePlugin) ScoreExtensions() framework.ScoreExtensions {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScoreExtensions")
	ret0, _ := ret[0].(framework.ScoreExtensions)
	return ret0
}

// ScoreExtensions indicates an expected call of ScoreExtensions.
func (mr *MockScorePluginMockRecorder) ScoreExtensions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScoreExtensions", reflect.TypeOf((*MockScorePlugin)(nil).ScoreExtensions))
}

// MockScoreExtensions is a mock of ScoreExtensions interface.
type MockScoreExtensions struct {
	ctrl     *gomock.Controller
	recorder *MockScoreExtensionsMockRecorder
	isgomock struct{}
}

// MockScoreExtensionsMockRecorder is the mock recorder for MockScoreExtensions.
type MockScoreExtensionsMockRecorder struct {
	mock *MockScoreExtensions
}

// NewMockScoreExtensions creates a new mock instance.
func NewMockScoreExtensions(ctrl *gomock.Controller) *MockScoreExtensions {
	mock := &MockScoreExtensions{ctrl: ctrl}
	mock.recorder = &MockScoreExtensionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScoreExtensions) EXPECT() *MockScoreExtensionsMockRecorder {
	return m.recorder
}

// NormalizeScore mocks base method.
func (m *MockScoreExtensions) NormalizeScore(ctx context.Context, state *framework.CycleState, p *v1.Pod, scores framework.NodeScoreList) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NormalizeScore", ctx, state, p, scores)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// NormalizeScore indicates an expected call of NormalizeScore.
func (mr *MockScoreExtensionsMockRecorder) NormalizeScore(ctx, state, p, scores any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NormalizeScore", reflect.TypeOf((*MockScoreExtensions)(nil).NormalizeScore), ctx, state, p, scores)
}

// MockPermitPlugin is a mock of PermitPlugin interface.
type MockPermitPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPermitPluginMockRecorder
	isgomock struct{}
}

// MockPermitPluginMockRecorder is the mock recorder for MockPermitPlugin.
type MockPermitPluginMockRecorder struct {
	mock *MockPermitPlugin
}

// NewMockPermitPlugin creates a new mock instance.
func NewMockPermitPlugin(ctrl *gomock.Controller) *MockPermitPlugin {
	mock := &MockPermitPlugin{ctrl: ctrl}
	mock.recorder = &MockPermitPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermitPlugin) EXPECT() *MockPermitPluginMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockPermitPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPermitPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPermitPlugin)(nil).Name))
}

// Permit mocks base method.
func (m *MockPermitPlugin) Permit(ctx context.Context, state *framework.CycleState, p *v1.Pod, nodeName string) (*framework.Status, time.Duration) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Permit", ctx, state, p, nodeName)
	ret0, _ := ret[0].(*framework.Status)
	ret1, _ := ret[1].(time.Duration)
	return ret0, ret1
}

// Permit indicates an expected call of Permit.
func (mr *MockPermitPluginMockRecorder) Permit(ctx, state, p, nodeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Permit", reflect.TypeOf((*MockPermitPlugin)(nil).Permit), ctx, state, p, nodeName)
}

// MockBindPlugin is a mock of BindPlugin interface.
type MockBindPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockBindPluginMockRecorder
	isgomock struct{}
}

// MockBindPluginMockRecorder is the mock recorder for MockBindPlugin.
type MockBindPluginMockRecorder struct {
	mock *MockBindPlugin
}

// NewMockBindPlugin creates a new mock instance.
func NewMockBindPlugin(ctrl *gomock.Controller) *MockBindPlugin {
	mock := &MockBindPlugin{ctrl: ctrl}
	mock.recorder = &MockBindPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBindPlugin) EXPECT() *MockBindPluginMockRecorder {
	return m.recorder
}

// Bind mocks base method.
func (m *MockBindPlugin) Bind(ctx context.Context, state *framework.CycleState, p *v1.Pod, nodeName string) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bind", ctx, state, p, nodeName)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// Bind indicates an expected call of Bind.
func (mr *MockBindPluginMockRecorder) Bind(ctx, state, p, nodeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bind", reflect.TypeOf((*MockBindPlugin)(nil).Bind), ctx, state, p, nodeName)
}

// Name mocks base method.
func (m *MockBindPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockBindPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockBindPlugin)(nil).Name))
}

// MockPreBindPlugin is a mock of PreBindPlugin interface.
type MockPreBindPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPreBindPluginMockRecorder
	isgomock struct{}
}

// MockPreBindPluginMockRecorder is the mock recorder for MockPreBindPlugin.
type MockPreBindPluginMockRecorder struct {
	mock *MockPreBindPlugin
}

// NewMockPreBindPlugin creates a new mock instance.
func NewMockPreBindPlugin(ctrl *gomock.Controller) *MockPreBindPlugin {
	mock := &MockPreBindPlugin{ctrl: ctrl}
	mock.recorder = &MockPreBindPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreBindPlugin) EXPECT() *MockPreBindPluginMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockPreBindPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPreBindPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPreBindPlugin)(nil).Name))
}

// PreBind mocks base method.
func (m *MockPreBindPlugin) PreBind(ctx context.Context, state *framework.CycleState, p *v1.Pod, nodeName string) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreBind", ctx, state, p, nodeName)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// PreBind indicates an expected call of PreBind.
func (mr *MockPreBindPluginMockRecorder) PreBind(ctx, state, p, nodeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreBind", reflect.TypeOf((*MockPreBindPlugin)(nil).PreBind), ctx, state, p, nodeName)
}

// MockPostBindPlugin is a mock of PostBindPlugin interface.
type MockPostBindPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPostBindPluginMockRecorder
	isgomock struct{}
}

// MockPostBindPluginMockRecorder is the mock recorder for MockPostBindPlugin.
type MockPostBindPluginMockRecorder struct {
	mock *MockPostBindPlugin
}

// NewMockPostBindPlugin creates a new mock instance.
func NewMockPostBindPlugin(ctrl *gomock.Controller) *MockPostBindPlugin {
	mock := &MockPostBindPlugin{ctrl: ctrl}
	mock.recorder = &MockPostBindPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostBindPlugin) EXPECT() *MockPostBindPluginMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockPostBindPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPostBindPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPostBindPlugin)(nil).Name))
}

// PostBind mocks base method.
func (m *MockPostBindPlugin) PostBind(ctx context.Context, state *framework.CycleState, p *v1.Pod, nodeName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PostBind", ctx, state, p, nodeName)
}

// PostBind indicates an expected call of PostBind.
func (mr *MockPostBindPluginMockRecorder) PostBind(ctx, state, p, nodeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostBind", reflect.TypeOf((*MockPostBindPlugin)(nil).PostBind), ctx, state, p, nodeName)
}

// MockReservePlugin is a mock of ReservePlugin interface.
type MockReservePlugin struct {
	ctrl     *gomock.Controller
	recorder *MockReservePluginMockRecorder
	isgomock struct{}
}

// MockReservePluginMockRecorder is the mock recorder for MockReservePlugin.
type MockReservePluginMockRecorder struct {
	mock *MockReservePlugin
}

// NewMockReservePlugin creates a new mock instance.
func NewMockReservePlugin(ctrl *gomock.Controller) *MockReservePlugin {
	mock := &MockReservePlugin{ctrl: ctrl}
	mock.recorder = &MockReservePluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservePlugin) EXPECT() *MockReservePluginMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockReservePlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockReservePluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockReservePlugin)(nil).Name))
}

// Reserve mocks base method.
func (m *MockReservePlugin) Reserve(ctx context.Context, state *framework.CycleState, p *v1.Pod, nodeName string) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reserve", ctx, state, p, nodeName)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// Reserve indicates an expected call of Reserve.
func (mr *MockReservePluginMockRecorder) Reserve(ctx, state, p, nodeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reserve", reflect.TypeOf((*MockReservePlugin)(nil).Reserve), ctx, state, p, nodeName)
}

// Unreserve mocks base method.
func (m *MockReservePlugin) Unreserve(ctx context.Context, state *framework.CycleState, p *v1.Pod, nodeName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unreserve", ctx, state, p, nodeName)
}

// Unreserve indicates an expected call of Unreserve.
func (mr *MockReservePluginMockRecorder) Unreserve(ctx, state, p, nodeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unreserve", reflect.TypeOf((*MockReservePlugin)(nil).Unreserve), ctx, state, p, nodeName)
}
