// Code generated by MockGen. DO NOT EDIT.
// Source: sigs.k8s.io/kube-scheduler-simulator/simulator/scheduler/plugin (interfaces: Store,PreFilterPluginExtender,FilterPluginExtender,PostFilterPluginExtender,PreScorePluginExtender,ScorePluginExtender,NormalizeScorePluginExtender,ReservePluginExtender,PermitPluginExtender,PreBindPluginExtender,BindPluginExtender,PostBindPluginExtender)

// Package plugin is a generated GoMock package.
package plugin

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/api/core/v1"
	framework "k8s.io/kubernetes/pkg/scheduler/framework"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddBindResult mocks base method.
func (m *MockStore) AddBindResult(arg0, arg1, arg2, arg3 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddBindResult", arg0, arg1, arg2, arg3)
}

// AddBindResult indicates an expected call of AddBindResult.
func (mr *MockStoreMockRecorder) AddBindResult(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBindResult", reflect.TypeOf((*MockStore)(nil).AddBindResult), arg0, arg1, arg2, arg3)
}

// AddCustomResult mocks base method.
func (m *MockStore) AddCustomResult(arg0, arg1, arg2, arg3 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCustomResult", arg0, arg1, arg2, arg3)
}

// AddCustomResult indicates an expected call of AddCustomResult.
func (mr *MockStoreMockRecorder) AddCustomResult(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCustomResult", reflect.TypeOf((*MockStore)(nil).AddCustomResult), arg0, arg1, arg2, arg3)
}

// AddFilterResult mocks base method.
func (m *MockStore) AddFilterResult(arg0, arg1, arg2, arg3, arg4 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddFilterResult", arg0, arg1, arg2, arg3, arg4)
}

// AddFilterResult indicates an expected call of AddFilterResult.
func (mr *MockStoreMockRecorder) AddFilterResult(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFilterResult", reflect.TypeOf((*MockStore)(nil).AddFilterResult), arg0, arg1, arg2, arg3, arg4)
}

// AddNormalizedScoreResult mocks base method.
func (m *MockStore) AddNormalizedScoreResult(arg0, arg1, arg2, arg3 string, arg4 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddNormalizedScoreResult", arg0, arg1, arg2, arg3, arg4)
}

// AddNormalizedScoreResult indicates an expected call of AddNormalizedScoreResult.
func (mr *MockStoreMockRecorder) AddNormalizedScoreResult(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNormalizedScoreResult", reflect.TypeOf((*MockStore)(nil).AddNormalizedScoreResult), arg0, arg1, arg2, arg3, arg4)
}

// AddPermitResult mocks base method.
func (m *MockStore) AddPermitResult(arg0, arg1, arg2, arg3 string, arg4 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddPermitResult", arg0, arg1, arg2, arg3, arg4)
}

// AddPermitResult indicates an expected call of AddPermitResult.
func (mr *MockStoreMockRecorder) AddPermitResult(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPermitResult", reflect.TypeOf((*MockStore)(nil).AddPermitResult), arg0, arg1, arg2, arg3, arg4)
}

// AddPostFilterResult mocks base method.
func (m *MockStore) AddPostFilterResult(arg0, arg1, arg2, arg3 string, arg4 []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddPostFilterResult", arg0, arg1, arg2, arg3, arg4)
}

// AddPostFilterResult indicates an expected call of AddPostFilterResult.
func (mr *MockStoreMockRecorder) AddPostFilterResult(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPostFilterResult", reflect.TypeOf((*MockStore)(nil).AddPostFilterResult), arg0, arg1, arg2, arg3, arg4)
}

// AddPreBindResult mocks base method.
func (m *MockStore) AddPreBindResult(arg0, arg1, arg2, arg3 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddPreBindResult", arg0, arg1, arg2, arg3)
}

// AddPreBindResult indicates an expected call of AddPreBindResult.
func (mr *MockStoreMockRecorder) AddPreBindResult(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPreBindResult", reflect.TypeOf((*MockStore)(nil).AddPreBindResult), arg0, arg1, arg2, arg3)
}

// AddPreFilterResult mocks base method.
func (m *MockStore) AddPreFilterResult(arg0, arg1, arg2, arg3 string, arg4 *framework.PreFilterResult) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddPreFilterResult", arg0, arg1, arg2, arg3, arg4)
}

// AddPreFilterResult indicates an expected call of AddPreFilterResult.
func (mr *MockStoreMockRecorder) AddPreFilterResult(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPreFilterResult", reflect.TypeOf((*MockStore)(nil).AddPreFilterResult), arg0, arg1, arg2, arg3, arg4)
}

// AddPreScoreResult mocks base method.
func (m *MockStore) AddPreScoreResult(arg0, arg1, arg2, arg3 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddPreScoreResult", arg0, arg1, arg2, arg3)
}

// AddPreScoreResult indicates an expected call of AddPreScoreResult.
func (mr *MockStoreMockRecorder) AddPreScoreResult(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPreScoreResult", reflect.TypeOf((*MockStore)(nil).AddPreScoreResult), arg0, arg1, arg2, arg3)
}

// AddReserveResult mocks base method.
func (m *MockStore) AddReserveResult(arg0, arg1, arg2, arg3 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddReserveResult", arg0, arg1, arg2, arg3)
}

// AddReserveResult indicates an expected call of AddReserveResult.
func (mr *MockStoreMockRecorder) AddReserveResult(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReserveResult", reflect.TypeOf((*MockStore)(nil).AddReserveResult), arg0, arg1, arg2, arg3)
}

// AddScoreResult mocks base method.
func (m *MockStore) AddScoreResult(arg0, arg1, arg2, arg3 string, arg4 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddScoreResult", arg0, arg1, arg2, arg3, arg4)
}

// AddScoreResult indicates an expected call of AddScoreResult.
func (mr *MockStoreMockRecorder) AddScoreResult(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddScoreResult", reflect.TypeOf((*MockStore)(nil).AddScoreResult), arg0, arg1, arg2, arg3, arg4)
}

// AddSelectedNode mocks base method.
func (m *MockStore) AddSelectedNode(arg0, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddSelectedNode", arg0, arg1, arg2)
}

// AddSelectedNode indicates an expected call of AddSelectedNode.
func (mr *MockStoreMockRecorder) AddSelectedNode(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSelectedNode", reflect.TypeOf((*MockStore)(nil).AddSelectedNode), arg0, arg1, arg2)
}

// MockPreFilterPluginExtender is a mock of PreFilterPluginExtender interface.
type MockPreFilterPluginExtender struct {
	ctrl     *gomock.Controller
	recorder *MockPreFilterPluginExtenderMockRecorder
}

// MockPreFilterPluginExtenderMockRecorder is the mock recorder for MockPreFilterPluginExtender.
type MockPreFilterPluginExtenderMockRecorder struct {
	mock *MockPreFilterPluginExtender
}

// NewMockPreFilterPluginExtender creates a new mock instance.
func NewMockPreFilterPluginExtender(ctrl *gomock.Controller) *MockPreFilterPluginExtender {
	mock := &MockPreFilterPluginExtender{ctrl: ctrl}
	mock.recorder = &MockPreFilterPluginExtenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreFilterPluginExtender) EXPECT() *MockPreFilterPluginExtenderMockRecorder {
	return m.recorder
}

// AfterPreFilter mocks base method.
func (m *MockPreFilterPluginExtender) AfterPreFilter(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 *framework.PreFilterResult, arg4 *framework.Status) (*framework.PreFilterResult, *framework.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterPreFilter", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*framework.PreFilterResult)
	ret1, _ := ret[1].(*framework.Status)
	return ret0, ret1
}

// AfterPreFilter indicates an expected call of AfterPreFilter.
func (mr *MockPreFilterPluginExtenderMockRecorder) AfterPreFilter(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterPreFilter", reflect.TypeOf((*MockPreFilterPluginExtender)(nil).AfterPreFilter), arg0, arg1, arg2, arg3, arg4)
}

// BeforePreFilter mocks base method.
func (m *MockPreFilterPluginExtender) BeforePreFilter(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod) (*framework.PreFilterResult, *framework.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforePreFilter", arg0, arg1, arg2)
	ret0, _ := ret[0].(*framework.PreFilterResult)
	ret1, _ := ret[1].(*framework.Status)
	return ret0, ret1
}

// BeforePreFilter indicates an expected call of BeforePreFilter.
func (mr *MockPreFilterPluginExtenderMockRecorder) BeforePreFilter(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforePreFilter", reflect.TypeOf((*MockPreFilterPluginExtender)(nil).BeforePreFilter), arg0, arg1, arg2)
}

// MockFilterPluginExtender is a mock of FilterPluginExtender interface.
type MockFilterPluginExtender struct {
	ctrl     *gomock.Controller
	recorder *MockFilterPluginExtenderMockRecorder
}

// MockFilterPluginExtenderMockRecorder is the mock recorder for MockFilterPluginExtender.
type MockFilterPluginExtenderMockRecorder struct {
	mock *MockFilterPluginExtender
}

// NewMockFilterPluginExtender creates a new mock instance.
func NewMockFilterPluginExtender(ctrl *gomock.Controller) *MockFilterPluginExtender {
	mock := &MockFilterPluginExtender{ctrl: ctrl}
	mock.recorder = &MockFilterPluginExtenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilterPluginExtender) EXPECT() *MockFilterPluginExtenderMockRecorder {
	return m.recorder
}

// AfterFilter mocks base method.
func (m *MockFilterPluginExtender) AfterFilter(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 *framework.NodeInfo, arg4 *framework.Status) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterFilter", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// AfterFilter indicates an expected call of AfterFilter.
func (mr *MockFilterPluginExtenderMockRecorder) AfterFilter(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterFilter", reflect.TypeOf((*MockFilterPluginExtender)(nil).AfterFilter), arg0, arg1, arg2, arg3, arg4)
}

// BeforeFilter mocks base method.
func (m *MockFilterPluginExtender) BeforeFilter(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 *framework.NodeInfo) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeFilter", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// BeforeFilter indicates an expected call of BeforeFilter.
func (mr *MockFilterPluginExtenderMockRecorder) BeforeFilter(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeFilter", reflect.TypeOf((*MockFilterPluginExtender)(nil).BeforeFilter), arg0, arg1, arg2, arg3)
}

// MockPostFilterPluginExtender is a mock of PostFilterPluginExtender interface.
type MockPostFilterPluginExtender struct {
	ctrl     *gomock.Controller
	recorder *MockPostFilterPluginExtenderMockRecorder
}

// MockPostFilterPluginExtenderMockRecorder is the mock recorder for MockPostFilterPluginExtender.
type MockPostFilterPluginExtenderMockRecorder struct {
	mock *MockPostFilterPluginExtender
}

// NewMockPostFilterPluginExtender creates a new mock instance.
func NewMockPostFilterPluginExtender(ctrl *gomock.Controller) *MockPostFilterPluginExtender {
	mock := &MockPostFilterPluginExtender{ctrl: ctrl}
	mock.recorder = &MockPostFilterPluginExtenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostFilterPluginExtender) EXPECT() *MockPostFilterPluginExtenderMockRecorder {
	return m.recorder
}

// AfterPostFilter mocks base method.
func (m *MockPostFilterPluginExtender) AfterPostFilter(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 framework.NodeToStatusMap, arg4 *framework.PostFilterResult, arg5 *framework.Status) (*framework.PostFilterResult, *framework.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterPostFilter", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*framework.PostFilterResult)
	ret1, _ := ret[1].(*framework.Status)
	return ret0, ret1
}

// AfterPostFilter indicates an expected call of AfterPostFilter.
func (mr *MockPostFilterPluginExtenderMockRecorder) AfterPostFilter(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterPostFilter", reflect.TypeOf((*MockPostFilterPluginExtender)(nil).AfterPostFilter), arg0, arg1, arg2, arg3, arg4, arg5)
}

// BeforePostFilter mocks base method.
func (m *MockPostFilterPluginExtender) BeforePostFilter(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 framework.NodeToStatusMap) (*framework.PostFilterResult, *framework.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforePostFilter", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*framework.PostFilterResult)
	ret1, _ := ret[1].(*framework.Status)
	return ret0, ret1
}

// BeforePostFilter indicates an expected call of BeforePostFilter.
func (mr *MockPostFilterPluginExtenderMockRecorder) BeforePostFilter(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforePostFilter", reflect.TypeOf((*MockPostFilterPluginExtender)(nil).BeforePostFilter), arg0, arg1, arg2, arg3)
}

// MockPreScorePluginExtender is a mock of PreScorePluginExtender interface.
type MockPreScorePluginExtender struct {
	ctrl     *gomock.Controller
	recorder *MockPreScorePluginExtenderMockRecorder
}

// MockPreScorePluginExtenderMockRecorder is the mock recorder for MockPreScorePluginExtender.
type MockPreScorePluginExtenderMockRecorder struct {
	mock *MockPreScorePluginExtender
}

// NewMockPreScorePluginExtender creates a new mock instance.
func NewMockPreScorePluginExtender(ctrl *gomock.Controller) *MockPreScorePluginExtender {
	mock := &MockPreScorePluginExtender{ctrl: ctrl}
	mock.recorder = &MockPreScorePluginExtenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreScorePluginExtender) EXPECT() *MockPreScorePluginExtenderMockRecorder {
	return m.recorder
}

// AfterPreScore mocks base method.
func (m *MockPreScorePluginExtender) AfterPreScore(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 []*framework.NodeInfo, arg4 *framework.Status) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterPreScore", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// AfterPreScore indicates an expected call of AfterPreScore.
func (mr *MockPreScorePluginExtenderMockRecorder) AfterPreScore(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterPreScore", reflect.TypeOf((*MockPreScorePluginExtender)(nil).AfterPreScore), arg0, arg1, arg2, arg3, arg4)
}

// BeforePreScore mocks base method.
func (m *MockPreScorePluginExtender) BeforePreScore(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 []*framework.NodeInfo) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforePreScore", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// BeforePreScore indicates an expected call of BeforePreScore.
func (mr *MockPreScorePluginExtenderMockRecorder) BeforePreScore(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforePreScore", reflect.TypeOf((*MockPreScorePluginExtender)(nil).BeforePreScore), arg0, arg1, arg2, arg3)
}

// MockScorePluginExtender is a mock of ScorePluginExtender interface.
type MockScorePluginExtender struct {
	ctrl     *gomock.Controller
	recorder *MockScorePluginExtenderMockRecorder
}

// MockScorePluginExtenderMockRecorder is the mock recorder for MockScorePluginExtender.
type MockScorePluginExtenderMockRecorder struct {
	mock *MockScorePluginExtender
}

// NewMockScorePluginExtender creates a new mock instance.
func NewMockScorePluginExtender(ctrl *gomock.Controller) *MockScorePluginExtender {
	mock := &MockScorePluginExtender{ctrl: ctrl}
	mock.recorder = &MockScorePluginExtenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScorePluginExtender) EXPECT() *MockScorePluginExtenderMockRecorder {
	return m.recorder
}

// AfterScore mocks base method.
func (m *MockScorePluginExtender) AfterScore(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 string, arg4 int64, arg5 *framework.Status) (int64, *framework.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterScore", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*framework.Status)
	return ret0, ret1
}

// AfterScore indicates an expected call of AfterScore.
func (mr *MockScorePluginExtenderMockRecorder) AfterScore(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterScore", reflect.TypeOf((*MockScorePluginExtender)(nil).AfterScore), arg0, arg1, arg2, arg3, arg4, arg5)
}

// BeforeScore mocks base method.
func (m *MockScorePluginExtender) BeforeScore(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 string) (int64, *framework.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeScore", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*framework.Status)
	return ret0, ret1
}

// BeforeScore indicates an expected call of BeforeScore.
func (mr *MockScorePluginExtenderMockRecorder) BeforeScore(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeScore", reflect.TypeOf((*MockScorePluginExtender)(nil).BeforeScore), arg0, arg1, arg2, arg3)
}

// MockNormalizeScorePluginExtender is a mock of NormalizeScorePluginExtender interface.
type MockNormalizeScorePluginExtender struct {
	ctrl     *gomock.Controller
	recorder *MockNormalizeScorePluginExtenderMockRecorder
}

// MockNormalizeScorePluginExtenderMockRecorder is the mock recorder for MockNormalizeScorePluginExtender.
type MockNormalizeScorePluginExtenderMockRecorder struct {
	mock *MockNormalizeScorePluginExtender
}

// NewMockNormalizeScorePluginExtender creates a new mock instance.
func NewMockNormalizeScorePluginExtender(ctrl *gomock.Controller) *MockNormalizeScorePluginExtender {
	mock := &MockNormalizeScorePluginExtender{ctrl: ctrl}
	mock.recorder = &MockNormalizeScorePluginExtenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNormalizeScorePluginExtender) EXPECT() *MockNormalizeScorePluginExtenderMockRecorder {
	return m.recorder
}

// AfterNormalizeScore mocks base method.
func (m *MockNormalizeScorePluginExtender) AfterNormalizeScore(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 framework.NodeScoreList, arg4 *framework.Status) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterNormalizeScore", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// AfterNormalizeScore indicates an expected call of AfterNormalizeScore.
func (mr *MockNormalizeScorePluginExtenderMockRecorder) AfterNormalizeScore(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterNormalizeScore", reflect.TypeOf((*MockNormalizeScorePluginExtender)(nil).AfterNormalizeScore), arg0, arg1, arg2, arg3, arg4)
}

// BeforeNormalizeScore mocks base method.
func (m *MockNormalizeScorePluginExtender) BeforeNormalizeScore(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 framework.NodeScoreList) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeNormalizeScore", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// BeforeNormalizeScore indicates an expected call of BeforeNormalizeScore.
func (mr *MockNormalizeScorePluginExtenderMockRecorder) BeforeNormalizeScore(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeNormalizeScore", reflect.TypeOf((*MockNormalizeScorePluginExtender)(nil).BeforeNormalizeScore), arg0, arg1, arg2, arg3)
}

// MockReservePluginExtender is a mock of ReservePluginExtender interface.
type MockReservePluginExtender struct {
	ctrl     *gomock.Controller
	recorder *MockReservePluginExtenderMockRecorder
}

// MockReservePluginExtenderMockRecorder is the mock recorder for MockReservePluginExtender.
type MockReservePluginExtenderMockRecorder struct {
	mock *MockReservePluginExtender
}

// NewMockReservePluginExtender creates a new mock instance.
func NewMockReservePluginExtender(ctrl *gomock.Controller) *MockReservePluginExtender {
	mock := &MockReservePluginExtender{ctrl: ctrl}
	mock.recorder = &MockReservePluginExtenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservePluginExtender) EXPECT() *MockReservePluginExtenderMockRecorder {
	return m.recorder
}

// AfterReserve mocks base method.
func (m *MockReservePluginExtender) AfterReserve(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 string, arg4 *framework.Status) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterReserve", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// AfterReserve indicates an expected call of AfterReserve.
func (mr *MockReservePluginExtenderMockRecorder) AfterReserve(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterReserve", reflect.TypeOf((*MockReservePluginExtender)(nil).AfterReserve), arg0, arg1, arg2, arg3, arg4)
}

// AfterUnreserve mocks base method.
func (m *MockReservePluginExtender) AfterUnreserve(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AfterUnreserve", arg0, arg1, arg2, arg3)
}

// AfterUnreserve indicates an expected call of AfterUnreserve.
func (mr *MockReservePluginExtenderMockRecorder) AfterUnreserve(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterUnreserve", reflect.TypeOf((*MockReservePluginExtender)(nil).AfterUnreserve), arg0, arg1, arg2, arg3)
}

// BeforeReserve mocks base method.
func (m *MockReservePluginExtender) BeforeReserve(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 string) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeReserve", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// BeforeReserve indicates an expected call of BeforeReserve.
func (mr *MockReservePluginExtenderMockRecorder) BeforeReserve(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeReserve", reflect.TypeOf((*MockReservePluginExtender)(nil).BeforeReserve), arg0, arg1, arg2, arg3)
}

// BeforeUnreserve mocks base method.
func (m *MockReservePluginExtender) BeforeUnreserve(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 string) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeUnreserve", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// BeforeUnreserve indicates an expected call of BeforeUnreserve.
func (mr *MockReservePluginExtenderMockRecorder) BeforeUnreserve(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeUnreserve", reflect.TypeOf((*MockReservePluginExtender)(nil).BeforeUnreserve), arg0, arg1, arg2, arg3)
}

// MockPermitPluginExtender is a mock of PermitPluginExtender interface.
type MockPermitPluginExtender struct {
	ctrl     *gomock.Controller
	recorder *MockPermitPluginExtenderMockRecorder
}

// MockPermitPluginExtenderMockRecorder is the mock recorder for MockPermitPluginExtender.
type MockPermitPluginExtenderMockRecorder struct {
	mock *MockPermitPluginExtender
}

// NewMockPermitPluginExtender creates a new mock instance.
func NewMockPermitPluginExtender(ctrl *gomock.Controller) *MockPermitPluginExtender {
	mock := &MockPermitPluginExtender{ctrl: ctrl}
	mock.recorder = &MockPermitPluginExtenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermitPluginExtender) EXPECT() *MockPermitPluginExtenderMockRecorder {
	return m.recorder
}

// AfterPermit mocks base method.
func (m *MockPermitPluginExtender) AfterPermit(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 string, arg4 *framework.Status, arg5 time.Duration) (*framework.Status, time.Duration) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterPermit", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*framework.Status)
	ret1, _ := ret[1].(time.Duration)
	return ret0, ret1
}

// AfterPermit indicates an expected call of AfterPermit.
func (mr *MockPermitPluginExtenderMockRecorder) AfterPermit(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterPermit", reflect.TypeOf((*MockPermitPluginExtender)(nil).AfterPermit), arg0, arg1, arg2, arg3, arg4, arg5)
}

// BeforePermit mocks base method.
func (m *MockPermitPluginExtender) BeforePermit(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 string) (*framework.Status, time.Duration) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforePermit", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*framework.Status)
	ret1, _ := ret[1].(time.Duration)
	return ret0, ret1
}

// BeforePermit indicates an expected call of BeforePermit.
func (mr *MockPermitPluginExtenderMockRecorder) BeforePermit(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforePermit", reflect.TypeOf((*MockPermitPluginExtender)(nil).BeforePermit), arg0, arg1, arg2, arg3)
}

// MockPreBindPluginExtender is a mock of PreBindPluginExtender interface.
type MockPreBindPluginExtender struct {
	ctrl     *gomock.Controller
	recorder *MockPreBindPluginExtenderMockRecorder
}

// MockPreBindPluginExtenderMockRecorder is the mock recorder for MockPreBindPluginExtender.
type MockPreBindPluginExtenderMockRecorder struct {
	mock *MockPreBindPluginExtender
}

// NewMockPreBindPluginExtender creates a new mock instance.
func NewMockPreBindPluginExtender(ctrl *gomock.Controller) *MockPreBindPluginExtender {
	mock := &MockPreBindPluginExtender{ctrl: ctrl}
	mock.recorder = &MockPreBindPluginExtenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreBindPluginExtender) EXPECT() *MockPreBindPluginExtenderMockRecorder {
	return m.recorder
}

// AfterPreBind mocks base method.
func (m *MockPreBindPluginExtender) AfterPreBind(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 string, arg4 *framework.Status) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterPreBind", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// AfterPreBind indicates an expected call of AfterPreBind.
func (mr *MockPreBindPluginExtenderMockRecorder) AfterPreBind(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterPreBind", reflect.TypeOf((*MockPreBindPluginExtender)(nil).AfterPreBind), arg0, arg1, arg2, arg3, arg4)
}

// BeforePreBind mocks base method.
func (m *MockPreBindPluginExtender) BeforePreBind(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 string) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforePreBind", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// BeforePreBind indicates an expected call of BeforePreBind.
func (mr *MockPreBindPluginExtenderMockRecorder) BeforePreBind(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforePreBind", reflect.TypeOf((*MockPreBindPluginExtender)(nil).BeforePreBind), arg0, arg1, arg2, arg3)
}

// MockBindPluginExtender is a mock of BindPluginExtender interface.
type MockBindPluginExtender struct {
	ctrl     *gomock.Controller
	recorder *MockBindPluginExtenderMockRecorder
}

// MockBindPluginExtenderMockRecorder is the mock recorder for MockBindPluginExtender.
type MockBindPluginExtenderMockRecorder struct {
	mock *MockBindPluginExtender
}

// NewMockBindPluginExtender creates a new mock instance.
func NewMockBindPluginExtender(ctrl *gomock.Controller) *MockBindPluginExtender {
	mock := &MockBindPluginExtender{ctrl: ctrl}
	mock.recorder = &MockBindPluginExtenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBindPluginExtender) EXPECT() *MockBindPluginExtenderMockRecorder {
	return m.recorder
}

// AfterBind mocks base method.
func (m *MockBindPluginExtender) AfterBind(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 string, arg4 *framework.Status) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterBind", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// AfterBind indicates an expected call of AfterBind.
func (mr *MockBindPluginExtenderMockRecorder) AfterBind(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterBind", reflect.TypeOf((*MockBindPluginExtender)(nil).AfterBind), arg0, arg1, arg2, arg3, arg4)
}

// BeforeBind mocks base method.
func (m *MockBindPluginExtender) BeforeBind(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 string) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeBind", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// BeforeBind indicates an expected call of BeforeBind.
func (mr *MockBindPluginExtenderMockRecorder) BeforeBind(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeBind", reflect.TypeOf((*MockBindPluginExtender)(nil).BeforeBind), arg0, arg1, arg2, arg3)
}

// MockPostBindPluginExtender is a mock of PostBindPluginExtender interface.
type MockPostBindPluginExtender struct {
	ctrl     *gomock.Controller
	recorder *MockPostBindPluginExtenderMockRecorder
}

// MockPostBindPluginExtenderMockRecorder is the mock recorder for MockPostBindPluginExtender.
type MockPostBindPluginExtenderMockRecorder struct {
	mock *MockPostBindPluginExtender
}

// NewMockPostBindPluginExtender creates a new mock instance.
func NewMockPostBindPluginExtender(ctrl *gomock.Controller) *MockPostBindPluginExtender {
	mock := &MockPostBindPluginExtender{ctrl: ctrl}
	mock.recorder = &MockPostBindPluginExtenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostBindPluginExtender) EXPECT() *MockPostBindPluginExtenderMockRecorder {
	return m.recorder
}

// AfterPostBind mocks base method.
func (m *MockPostBindPluginExtender) AfterPostBind(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AfterPostBind", arg0, arg1, arg2, arg3)
}

// AfterPostBind indicates an expected call of AfterPostBind.
func (mr *MockPostBindPluginExtenderMockRecorder) AfterPostBind(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterPostBind", reflect.TypeOf((*MockPostBindPluginExtender)(nil).AfterPostBind), arg0, arg1, arg2, arg3)
}

// BeforePostBind mocks base method.
func (m *MockPostBindPluginExtender) BeforePostBind(arg0 context.Context, arg1 *framework.CycleState, arg2 *v1.Pod, arg3 string) *framework.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforePostBind", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*framework.Status)
	return ret0
}

// BeforePostBind indicates an expected call of BeforePostBind.
func (mr *MockPostBindPluginExtenderMockRecorder) BeforePostBind(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforePostBind", reflect.TypeOf((*MockPostBindPluginExtender)(nil).BeforePostBind), arg0, arg1, arg2, arg3)
}
