apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: scenario-system
spec:
  template:
    spec:
      volumes:
      - name: webhook-certs
        secret:
          secretName: webhook-certs
      containers:
      - name: manager
        volumeMounts:
        - name: webhook-certs
          mountPath: /tmp/k8s-webhook-server/serving-certs
          readOnly: true
