apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: scenario
    app.kubernetes.io/managed-by: kustomize
  name: scenario-webhook-service
  namespace: scenario-system
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - port: 9443
      protocol: TCP
      targetPort: 9443
